apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    # - host: patrikrepasky.tech
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-static-web
                port:
                  number: 8080
