apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web
  labels: 
    app: static-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-web
  template:
    metadata:
      labels:
        app: static-web
    spec:
      containers:
      - name: static-web
        image: {{.Values.appimage}}:{{.Values.apptag}}
        ports:
        - name: static-web-port
          containerPort: 80
